name: Codacy Analysis

on:
  push:
    branches:
      - master  # Specify the branch you want to trigger the workflow on commits

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Specify the JDK distribution, e.g., adopt, amazon-corretto, openjdk, etc.
        java-version: '8'    # Specify the Java version
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build, test, and generate Jacoco coverage report
      run: mvn clean verify jacoco:report

    - name: Upload service coverage
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: target/site/jacoco/jacoco.xml
